//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/swift-VIPER-Coordinator-template
//

import UIKit
import uCore

struct ___VARIABLE_moduleName___Configurator {

    static func createModule(
        output: ___VARIABLE_moduleName___ModuleOutput? = nil
    ) -> (view: UIViewController & Coordinating, input: ___VARIABLE_moduleName___ModuleInput) {
        let storyboard = UIStoryboard(name: "___VARIABLE_moduleName___", bundle: Bundle.module)

        guard let viewController = storyboard.instantiateInitialViewController() else {
            fatalError("___VARIABLE_moduleName___.storyboard has no initial view controller")
        }

        guard let view = viewController as? ___VARIABLE_moduleName___ViewController else {
            fatalError("Failed to cast to ___VARIABLE_moduleName___ViewController")
        }

        let interactor = ___VARIABLE_moduleName___Interactor()
        let presenter = ___VARIABLE_moduleName___Presenter(interface: view,
                                                           interactor: interactor,
                                                           output: output)

        view.presenter = presenter
        interactor.presenter = presenter

        return (view, presenter)
    }
}
