//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/swift-VIPER-Coordinator-template
//

import UIKit
import uCore

#warning("Move to ___VARIABLE_moduleName___Interfaces target")
// MARK: - ___VARIABLE_moduleName___CoordinatorOutput
public struct ___VARIABLE_moduleName___CoordinatorOutput {

    //    func didSelectResult: (_ result: Int) -> Void
}

// MARK: - ___VARIABLE_moduleName___Coordinator
public final class ___VARIABLE_moduleName___Coordinator: BaseCoordinator {

    private let output: ___VARIABLE_moduleName___CoordinatorOutput?
    private weak var input: ___VARIABLE_moduleName___ModuleInput?

    public init(
        router: Routable,
        output: ___VARIABLE_moduleName___CoordinatorOutput? = nil
    ) {
        self.output = output
        super.init(router: router)
    }
}

// MARK: - Coordinatable
extension ___VARIABLE_moduleName___Coordinator: Coordinatable {

    public func start() {
        let module = ___VARIABLE_moduleName___Configurator.createModule(output: nil)
        module.view.coordinator = self
        router.push(module.view, animated: true)
        input = module.input
    }
}
