//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/swift-VIPER-Coordinator-template
//

import UIKit
import uCore

struct ___VARIABLE_moduleName___Configurator {

    static func createModule(
        output: ___VARIABLE_moduleName___ModuleOutput? = nil
    ) -> (view: UIViewController & Coordinating, input: ___VARIABLE_moduleName___ModuleInput) {
        let view = ___VARIABLE_moduleName___ViewController()

        let interactor = ___VARIABLE_moduleName___Interactor()
        let presenter = ___VARIABLE_moduleName___Presenter(
            interface: view,
            interactor: interactor,
            output: output
        )

        view.presenter = presenter
        interactor.presenter = presenter

        return (view, presenter)
    }
}
