//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/swift-VIPER-Coordinator-template
//

import UIKit

public protocol ___VARIABLE_moduleName___CoordinatorOutput: AnyObject {

//    func didSelectResult(_ result: Int)
}

public final class ___VARIABLE_moduleName___Coordinator: BaseCoordinator, ___VARIABLE_moduleName___CoordinatorOutput {

    weak var delegate: ___VARIABLE_moduleName___CoordinatorOutput?

    public init(
        router: Router,
        delegate: ___VARIABLE_moduleName___CoordinatorOutput? = nil
    ) {
        self.delegate = delegate
        super.init(router: router)
    }
}

// MARK: - Coordinatable
extension ___VARIABLE_moduleName___Coordinator: Coordinatable {

    public func start() {
        let module = ___VARIABLE_moduleName___Configurator.createModule(delegate: self)
        router.setRootModule(module)
    }
}

// MARK: - ___VARIABLE_moduleName___Delegate
extension ___VARIABLE_moduleName___Coordinator: ___VARIABLE_moduleName___Delegate {

}
